### ISSUE TITLE
Remove `align` from `MemoryInterface::Store`, `MemoryInterface::Load`, `PlaceType`, etc.

### ISSUE THREAD

**Issue by JakobDegen** [RalfJung/minirust#5] opened 2022-06-09 01:18 UTC
I don't see the need for this complexity. I had considered this when doing MIR documentation too, but intentionally left it out. Instead, I think we should have minimum alignment be a fact that can be proven from the remainder of the semantics, and not a part of the semantics itself. Specifically, we need to enforce two things:

 1. Allocations for locals are suitably aligned (as required by the type)
 2. Places created by dereferencing a pointer are suitably aligned (except for unaligned accesses or such).

This should suffice to allow a backend to *prove* that reads are generally suitable aligned. For example, consider

```rust
struct S {
    a: u16,
    b: u32,
}
```

An access like `load(_3.a)` is necessarily aligned to 2 bytes, as `_3` is guaranteed to be aligned to 4 bytes (since `_3` is the return value of a suitable allocation), and the offset of `a` - which the backend can compute - is eg 2.

If we add `#[repr(packed)]` to the above struct, the same reasoning will fail, and so the backend cannot assume the load has this alignment.

**Comment by RalfJung** [comment] 2022-06-09 01:29
>  I think we should have minimum alignment be a fact that can be proven from the remainder of the semantics, and not a part of the semantics itself. 

I am not exactly sure what you mean by that, but under every interpretation I can imagine, this would mean the program cannot actually violate alignment requirements -- which is evidently not what actually happens.

*Something* needs to forbid unaligned loads from raw pointers, while allowing unaligned loads from fields of packed structs. I don't know a more elegant way to do that than what I currently have implemented.

**Comment by JakobDegen** [comment] 2022-06-09 01:43
Sorry, I should have been more clear. I propose we:

 1. Allocate locals with sufficient alignment for the type.
 2. Check alignment as a part of reference (and Box) validity.
 3. Check alignment on `Rvalue::Ref` and `Rvalue::AddrOf`
 4. Check alignment when dereferencing a pointer or reference (except for explicitly unaligned pointer reads, of course).

I claim that all the other alignment checks that we include now are unnecessary, since they cannot fail.

**Comment by RalfJung** [comment] 2022-06-11 01:38
> Check alignment on Rvalue::Ref and Rvalue::AddrOf

`AddrOf` explicitly does *not* check alignment. That is the main reason why it got added to the language.

**Comment by RalfJung** [comment] 2022-06-11 02:00
To be more concrete, here are some reference tests. (This is where I wish MiniRust was executable. Oh well. Just imagine this to be translated to MiniRust on the hopefully obvious way.)

This should be allowed:
```rust
#[repr(packed)]
struct P { f: u32 }

fn main() {
  let p = P { f: 0 }; // in general, alignment 1 but not 4
  let val = p.f;
  let ptr = addr_of!(p.f);
}
```
But if you add `*ptr` at the end, that is UB.

**Comment by RalfJung** [comment] 2022-06-11 02:10
So, I don't think we can remove it from `PlaceType`.

But we can remove it from `load` and `store`, if we have an invariant that all `PlaceExpr` are aligned and their `type.align`. Then checking that again is obviously redundant. I think that invariant holds with the current semantics. (There might be other operations that also `load`/`store`; they would have to remember to do their own alignment checks then.)

However, I am not sure if want that invariant -- that's basically https://github.com/rust-lang/unsafe-code-guidelines/issues/319, but for alignment. I am of the opinion that we should remove the `mem.layout_dereferenceable` check from `Deref`, so alignment (and dereferenceability in general) only becomes relevant on actual loads/stores. But that would require us to change codegen and use `getelementptr` instead of `getelementptr inbounds` when compiling place expressions that are "based on" a raw pointer.

If we don't have that invariant, we could of course still factor the alignment checks out of the memory interface and do them before calling `mem.{load,store}`. Maybe that would make sense. I wrote the memory interface when I thought of size and alignment as being on fairly equal footing, but have since abandoned that position (as is apparent in `Type` vs `PlaceType`), so it would make sense to revisit the memory interface and remove all alignment from it (and do the alignment checks all in `lang` instead). But I don't think that is what you are proposing.

**Comment by JakobDegen** [comment] 2022-06-11 02:55
```rust
AddrOf explicitly does not check alignment. That is the main reason why it got added to the language.
```

Ah, I thought it was just for `inbounds` reasons. That's fine though, doesn't matter either way.

Hm, I agree with you that we need to retain it if we don't want to do alignment checks on raw pointer derefs. I'm not so sure I want that, and the complexity that it introduces here is at least one of the reasons. "References must be aligned and raw pointers must be aligned when derefed" is easy to teach, and the simplicity of it would be reflected in the theoretical model. The alternative would be "your alignment obligation propagates along the place expression computation in this way:".

In any case, does my point at least make sense if we did do alignment checks on pointer derefs? If so, it probably makes sense to postpone this issue until that is decided.

**Comment by RalfJung** [comment] 2022-06-11 03:28
It makes sense for memory's `load` and `store`.

I don't see how it would get rid of `PlaceType`'s `align`.

**Comment by RalfJung** [comment] 2022-06-11 03:32
Hm okay looking at my step function, I though `Deref` needed the `align` from `PlaceType`, but in fact it *sets* that alignment for the place it has just created.

So yeah I guess you are right; if we do the alignment checks eagerly on place creation then we don't need to track place alignment and we don't need to check it on loads/stores. (In fact I pretty much wrote this back in https://github.com/rust-lang/rust/issues/63085 but it seems I had to re-learn that lesson.)

**Comment by RalfJung** [comment] 2022-06-11 03:36
> Hm, I agree with you that we need to retain it if we don't want to do alignment checks on raw pointer derefs. I'm not so sure I want that though, and the complexity that it introduces here is at least one of the reasons. "References must be aligned and raw pointers must be aligned when derefed" is easy to teach, and the simplicity of it would be reflected in the theoretical model. The alternative would be "your alignment obligation propagates along the place expression computation in this way:".

Well, we could also again do the "tower of weakenings" thing and have simple rules that we can explain, and more complicated rules that allow slightly more things for when that is really needed.

Quite a few people were surprised when I told them that `addr_of!(*ptr)` can be UB, so there is evidence that what seems like the simpler rules is actually not what people intuitively expect.

**Comment by JakobDegen** [comment] 2022-06-11 03:40
Ok, yeah, sounds like we're on the same page then.

> Quite a few people were surprised when I told them that addr_of!(*ptr) can be UB, so there is evidence that what seems like the simpler rules is actually not what people intuitively expect.

To be honest, I'd much rather fix these issues by helping people not dereference pointers when they don't intend to load/store. I am quite the fan of Gankra's proposal for built-in pointer offsetting via `p~field` or similar.

**Comment by RalfJung** [comment] 2022-06-11 04:04
I am a big fan of that proposal, too.

But I'd also like to remove the UB as well. "It is easier to teach" is IMO not a great reason to have more UB.

**Comment by RalfJung** [comment] 2022-06-11 04:24
> I am of the opinion that we should remove the mem.layout_dereferenceable check from Deref

FWIW I did that now, in a way that is still compatible with what codegen currently does. It's not so bad in terms of spec complexity, actually -- only the emergent behavior is complicated.

**Comment by JakobDegen** [comment] 2022-06-11 23:08
One thing I would note is that I would be interested in seeing how much perf we lose if we stop emitting inbounds for gep based on a raw pointer. Afaik there's no fundamental reason that this should cause any serious regressions, but that doesn't mean that it won't anyway

**Comment by RalfJung** [comment] 2022-06-12 18:06
Yeah -- but that's a question for https://github.com/rust-lang/unsafe-code-guidelines/issues/319.

For MiniRust, I think I'll close this as "works as intended" for now. There is a TODO in there to note that this is still an open question.

**Closed by RalfJung** 2022-06-12 18:06 UTC
